name: Auto Merge Codex PRs

on:
  pull_request:
    types: [opened, labeled, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    permissions:
      contents: write
      pull-requests: write
      checks: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Auto approve codex PRs
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --body "🚀 Red hack team auto-approval: Codex PR detected, merging automatically!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Wait for checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'python-app'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,neutral,skipped

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest
          
      - name: Auto merge codex PRs  
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --auto --delete-branch
          echo "🎯 Red hack team: Codex PR #${{ github.event.pull_request.number }} merged automatically!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}