name: Auto review and merge Codex PRs

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  review:
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Auto approve
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Auto fix Python
        run: python scripts/auto_fix_python.py

      - name: Commit fixes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          if [[ $(git status --porcelain) ]]; then
            git commit -am 'chore: auto format'
            git push
          fi

      - name: Run tests
        run: pytest -q

  merge:
    needs: review
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
